version: '3.3'

services:

    redisserver:
      container_name: redisserver
      image: redis:7.2
      ports: 
        - 6380:6380
      networks:
        - main
      volumes:
        - redisserver_data:/data


networks:
  main:

volumes:
  redisserver_data: